Create database TECHNICALASSESSMENT

use TECHNICALASSESSMENT

CREATE TABLE ExceptionHandling(
ExceptionID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Method VARCHAR(200) NULL,
Module VARCHAR(200) NULL,
ExceptionMessage VARCHAR(200) NULL,
ExceptionSource VARCHAR(200) NULL,
ExceptionStackTrace VARCHAR(200) NULL,
TargetSiteName VARCHAR(200) NULL,
CreatedDate DATETIME
);

CREATE TABLE Book(
BookID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Publisher VARCHAR(200) NULL,
Title VARCHAR(200) NULL,
AuthorLastName VARCHAR(100) NULL,
AuthorFirstName VARCHAR(100) NULL,
Price INT,
CreatedDate DATETIME,
UpdatedDate DATETIME
);
